# .github/actions/setup-node-and-install/action.yml
name: 'Setup and Install'
description: 'Check out code, set up Node, and install dependencies'
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: "22"
        cache: "npm"
    - shell: bash
      run: npm ci